---
title: "Homework 1 Answers"
subtitle: "BSTA 550"
date-modified: "today"
format:
  html:
    toc: true
    embed-resources: true
    link-external-newwindow: true
editor_options:
  chunk_output_type: console
---

```{=html}
<style>
div.answer { background-color: #f8eded; border-left: 4px solid #8B0000; border-radius: 5px; padding: 1em 1em 1em 1em;}
</style>
```

## Questions

### 1. Outcomes, events, and sample space

In the below parts, please list (i) one specific outcome, (ii) one event that contains more than one outcome, and (iii) the sample space.

#### Part a

Chris has a 5-pack of Gatorade sports drink: 1 orange, 2 lemon-lime, and 2 fruit punch. He blindly grabs one out of the pack over and over if necessary, without replacement, until he finds an orange one. *Note, each lemon-lime is indistinguishable, and each fruit punch is indistinguishable.*

::: answer
Let $L$ = Lemon-Lime, $P$ = Fruit Punch, and $O$ = Orange. Since $L$ and $P$ are indistinguishable, we do not need include more information on the two bottles.

##### i. Specific Outcome
$(L, P, O)$ OR $(P, O)$

##### ii. Event with More Than One Outcome

##### iii. Sample Space ($\Omega$)
19 total outcomes
:::

#### Part b

A claw machine contains 10 plush toys: 5 Red Squishies (R), 3 Blue Dinosaurs (B), and 2 Yellow Star Puffs (Y). You successfully grab a toy, remove it, and then grab a second toy (sampling without replacement). The result is the ordered pair of the two toys' colors.

::: answer
##### i. Specific Outcome
(R, Y) OR (B, R)

##### ii. Event with More Than One Outcome

##### iii. Sample Space ($\Omega$)
9 total outcomes
:::

#### Part c

You are opening a series of [mofusound Cat blind boxes](https://www.youtube.com/watch?v=wmehgHl8hj4). There are 4 possible figurines to collect: 1 shark cat (S), 1 orange striped fish cat (O), 1 hen cat (H), and 1 cow cat (C). You buy a single blind box.

::: answer
##### i. Specific Outcome
S (Shark Cat) OR O (Orange Striped Fish Cat)

##### ii. Event with More Than One Outcome

##### iii. Sample Space ($\Omega$)
4 total outcomes
:::

### 2. Running a simulation!

::: answer
We'll all have slightly different answers, but with 100,000 simulations, I got the probability of 0.489.
:::
