---
title: "Schedule"
format: 
  html:
    page-layout: full
    link-external-newwindow: true
    toc: true
    highlight-style: ayu
---

```{css, echo=FALSE}
.title{
  font-size: 30px;
  color: #006a4e;
  background-color: #fff;
  padding: 0px;
}

.sched table tbody tr:has(.rbasics) td:nth-child(4){
  background-color: #fcf2f7 !important;
  color: #EF85B3; 
}

.sched table tbody tr:has(.info) td:nth-child(4){
  background-color: #F8F9FA !important;
  color: #6C757D; 
}

.sched table tbody tr:has(.randr) td:nth-child(4){
  background-color: #FCF3E2 !important;
  color: #F39C12; 
}

.sched table tbody tr:has(.bestpract) td:nth-child(4){
  background-color: #DAECFE !important;
  color: #5BAFF8; 
}

.sched table tbody tr:has(.trans) td:nth-child(4){
  background-color: #D0DDF1 !important;
  color: #3070BF; 
}

.sched table tbody tr:has(.summ) td:nth-child(4){
  background-color: #D9E8E9 !important;
  color: #459B99; 
}

.sched table tbody tr:has(.viz) td:nth-child(4){
  background-color: #FFE6E6 !important;
  color: #C83532; 
}

.sched table tbody tr:has(.pract-row) td,
.sched table tbody tr:has(.lab-row) td{
  background-color: #FCF6F1 !important;
  color: #E89543;
}

.sched table tbody tr:has(.quiz-row) td{
  background-color: #F4F7FC !important;
  color: #6B8CC4;
}

.sched table tbody tr:has(.proj-row) td{
  background-color: #FEF6F7 !important;
  color: #F08897;
}

.sched table tbody tr:has(.week-row) td{
  background-color: #006a4e !important; /* A light red; use 'red' for bright red */
  color: #fff; 
  font-size: 0px;     /* Collapses the text height */
  height: 5px;
}

.sched table th:nth-of-type(1) {
  width: 5% !important;
}
.sched table th:nth-of-type(2) {
  width: 5% !important;
}
.sched table th:nth-of-type(3) {
  width: 5% !important;
}
.sched table th:nth-of-type(4) {
  width: 5% !important;
}
.sched table th:nth-of-type(5) {
  width: 5% !important;
}
.sched table th:nth-of-type(6) {
  width: 5% !important;
}
.sched table th:nth-of-type(7) {
  width: 30% !important;
}
.sched table th:nth-of-type(8) {
  width: 10% !important;
}
.sched table th:nth-of-type(9) {
  width: 5% !important;
}
.sched table th:nth-of-type(10) {
  width: 5% !important;
}
.sched table th:nth-of-type(11) {
  width: 5% !important;
}
.sched table th:nth-of-type(12) {
  width: 5% !important;
}
```

```{r setup, include=FALSE}
library(here)
source(here("class_dates.R"))
```

::: sched
| Week | Date | Key Info | Exit tix | Record-ing | Les-son | Topic | [TB](https://bookdown.org/kevin_davisross/probsim-book/) | Slides HTML | Slides PDF | Slides Notes | Muddy Points |
|:---|:---|:--:|:--:|:--:|:---|:---|----|:--:|:--:|:--:|:--:|
| 1 | `{r} w1d1 %>% format("%m/%d")` | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/00_Intro/00_Intro_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUOUcyWVVIQU5QR0lGSU4zWjE5M0dIWlMzRiQlQCNjPTEu)]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | 0 | Welcome |  | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/00_Intro/00_Intro.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/00_Intro/00_Intro.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  |  | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | 1 | Introduction to Probability | 1.1, 2.1, 2.2, 2.4.1 | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/01_Probability/01_Probability.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/01_Probability/01_Probability.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/01_Probability/01_Probability_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/01_Probability/01_Probability_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | `{r} w1d2 %>% format("%m/%d")` | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/02_Simulations/02_Simulations_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhURUlRNE04N1dFT0JMTVhZMk40SVYxV1JIViQlQCNjPTEu)]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | 2 | Introduction to Simulations | 2.3, 2.5 | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/02_Simulations/02_Simulations.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/02_Simulations/02_Simulations.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/02_Simulations/02_Simulations_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/02_Simulations/02_Simulations_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | **`r hw0 %>% format("%m/%d")`** |  |  |  |  | [**HW 0 due 11pm**]{.pract-row} |  |  |  |  |  |
| [ ]{.week-row} |  |  |  |  |  |  |  |  |  |  |  |
| 2 | `{r} w2d1 %>% format("%m/%d")` | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | 3 | Language of Probability | 2.2, 2.4 | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/03_Lang_prob/03_Lang_prob.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/03_Lang_prob/03_Lang_prob.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/03_Lang_prob/03_Lang_prob_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/03_Lang_prob/03_Lang_prob_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | `{r} w2d2 %>% format("%m/%d")` | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | 4 | Rules of Probability | 2.7, 3.3-3.5 | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/04_Rules_of_prob/04_Rules_of_prob.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/04_Rules_of_prob/04_Rules_of_prob.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/04_Rules_of_prob/04_Rules_of_prob_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/04_Rules_of_prob/04_Rules_of_prob_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | **`r hw1 %>% format("%m/%d")`** |  |  |  |  | [**HW 1 due 11pm**]{.pract-row} |  |  |  |  |  |
|  | **`r cp0 %>% format("%m/%d")`** |  |  |  |  | [**Checkpoint 0 due 11pm**]{.proj-row} |  |  |  |  |  |
| [ ]{.week-row} |  |  |  |  |  | Nicky on vacation this week |  |  |  |  |  |
| 3 | `r w3d1 %>% format("%m/%d")` | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | 6 | Async optional video: Calculus Review |  | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/06_Calculus_review/06_Calculus_review.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/06_Calculus_review/06_Calculus_review.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/06_Calculus_review/06_Calculus_review_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/06_Calculus_review/06_Calculus_review_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | `r w3d2 %>% format("%m/%d")` | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | 5 | Virtual class: Equally Likely Outcomes | 3.6 | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/05_Equally_likely_outcomes/05_Equally_likely_outcomes.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/05_Equally_likely_outcomes/05_Equally_likely_outcomes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/05_Equally_likely_outcomes/05_Equally_likely_outcomes_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/05_Equally_likely_outcomes/05_Equally_likely_outcomes_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | **`r cp1 %>% format("%m/%d")`** |  |  |  |  | [**Checkpoint 1 due 11pm**]{.proj-row} |  |  |  |  |  |
| [ ]{.week-row} |  |  |  |  |  | Nicky out of town, but can answer emails |  |  |  |  |  |
| 4 | `r w4d1 %>% format("%m/%d")` | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | 7 | pmfs | 4.1, 4.2 | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/07_pmfs/07_pmfs.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/07_pmfs/07_pmfs.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/07_pmfs/07_pmfs_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/07_pmfs/07_pmfs_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  |  |  |  | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | 8 | pdfs | 4.3 | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/08_pdfs/08_pdfs.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/08_pdfs/08_pdfs.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/08_pdfs/08_pdfs_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/08_pdfs/08_pdfs_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | `r w4d2 %>% format("%m/%d")` | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | 9 | CDFs | 4.4 | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/09_CDFs/09_CDFs.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/09_CDFs/09_CDFs.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/09_CDFs/09_CDFs_notes.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | **`r q1_open %>% format("%m/%d")`** |  |  |  |  | [**Quiz 1 opens \@ 3pm**]{.quiz-row} |  |  |  |  |  |
|  | [**`r hw2 %>% format("%m/%d")`**]{.pract-row} |  |  |  |  | **HW 2 due 11 pm** |  |  |  |  |  |
|  | [**`r q1_close %>% format("%m/%d")`**]{.quiz-row} |  |  |  |  | **Quiz 1 closes \@ 11pm** |  |  |  |  |  |
| [ ]{.week-row} |  |  |  |  |  |  |  |  |  |  |  |
| 5 | `r w5d1 %>% format("%m/%d")` | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | 13 | Expected Values | 5.1 | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/13_Expected_Values/13_Expected_Values.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/13_Expected_Values/13_Expected_Values.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/13_Expected_Values/13_Expected_Values_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/13_Expected_Values/13_Expected_Values_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | `r w5d2 %>% format("%m/%d")` | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | 14 | Variance | 5.2, 5.3 | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/14_Variance/14_Variance.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/14_Variance/14_Variance.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/14_Variance/14_Variance_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/14_Variance/14_Variance_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | **`r hw3 %>% format("%m/%d")`** |  |  |  |  | [**HW 3 due 11 pm**]{.pract-row} |  |  |  |  |  |
| [ ]{.week-row} |  |  |  |  |  |  |  |  |  |  |  |
| 6 | `r w6d1 %>% format("%m/%d")` | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | 15 | Important discrete RVs | 6 | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/15_Discrete_RVs/15_Discrete_RVs.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/15_Discrete_RVs/15_Discrete_RVs.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/15_Discrete_RVs/15_Discrete_RVs_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/15_Discrete_RVs/15_Discrete_RVs_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | `r w6d2 %>% format("%m/%d")` | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | 16 | Important continuous RVS | 7 | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/16_Cont_RVs/16_Cont_RVs.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/16_Cont_RVs/16_Cont_RVs.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/16_Cont_RVs/16_Cont_RVs_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/16_Cont_RVs/16_Cont_RVs_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | [**`r q2_open %>% format("%m/%d")`**]{.quiz-row} |  |  |  |  | **Quiz 2 opens \@ 11pm** |  |  |  |  |  |
|  | [**`r hw4 %>% format("%m/%d")`**]{.pract-row} |  |  |  |  | **HW 4 due 11 pm** |  |  |  |  |  |
|  | [**`r q2_close %>% format("%m/%d")`**]{.quiz-row} |  |  |  |  | **Quiz 2 closes \@ 11pm** |  |  |  |  |  |
| [ ]{.week-row} |  |  |  |  |  |  |  |  |  |  |  |
| 7 | `r w7d1 %>% format("%m/%d")` | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | 10 | Transformations of distributions | 4.6 | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/10_Transformations/10_Transformations.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/10_Transformations/10_Transformations.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/10_Transformations/10_Transformations_notes.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | `r w7d2 %>% format("%m/%d")` | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | 11 | Joint distributions | 4.7 | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/11_Joint_distributions/11_Joint_distributions.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/11_Joint_distributions/11_Joint_distributions.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/11_Joint_distributions/11_Joint_distributions_notes.pdf)]{style="color:#f8f5f0;"} [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/11_Joint_distributions/11_Joint_distributions_notes_02.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/11_Joint_distributions/11_Joint_distributions_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | **`r cp2 %>% format("%m/%d")`** |  |  |  |  | [**Checkpoint 2 due 11pm**]{.proj-row} |  |  |  |  |  |
| [ ]{.week-row} |  |  |  |  |  |  |  |  |  |  |  |
| 8 | `r w8d1 %>% format("%m/%d")` | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | 12 | Independence and Conditioning | 4.8, 4.9 | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/12_Independence_Conditioning/12_Independence_conditioning.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/12_Independence_Conditioning/12_Independence_conditioning.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/12_Independence_Conditioning/12_Independence_conditioning_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/12_Independence_Conditioning/12_Independence_conditioning_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | `r w8d2 %>% format("%m/%d")` | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} |  | Catch-up day |  | [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**`r hw5 %>% format("%m/%d")`**]{.pract-row} |  |  |  |  | **HW 5 due 11 pm** |  |  |  |  |  |
| [ ]{.week-row} |  |  |  |  |  |  |  |  |  |  |  |
| 9 | `r w9d1 %>% format("%m/%d")` | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | 17 | Central limit theorem | 8.1 | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/17_Central_Limit_Theorem/17_Central_Limit_Theorem.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/17_Central_Limit_Theorem/17_Central_Limit_Theorem.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/17_Central_Limit_Theorem/17_Central_Limit_Theorem_notes.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | `r w9d2 %>% format("%m/%d")` |  |  |  |  | No class |  |  |  |  |  |
|  | **`r cp3 %>% format("%m/%d")`** |  |  |  |  | [**Checkpoint 3 due 11pm**]{.proj-row} |  |  |  |  |  |
| [ ]{.week-row} |  |  |  |  |  |  |  |  |  |  |  |
| 10 | `r w10d1 %>% format("%m/%d")` | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | 18 | Moment Generating functions |  | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/18_Moment_Generating_Functions/18_Moment_Generating_Functions.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/18_Moment_Generating_Functions/18_Moment_Generating_Functions.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/18_Moment_Generating_Functions/18_Moment_Generating_Functions_notes.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | `r w10d2 %>% format("%m/%d")` | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} |  | Catch-up day |  | [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**`r q3_open %>% format("%m/%d")`**]{.quiz-row} |  |  |  |  | **Quiz 3 opens \@ 3pm** |  |  |  |  |  |
|  | [**`r hw6 %>% format("%m/%d")`**]{.pract-row} |  |  |  |  | **HW 6 due 11 pm** |  |  |  |  |  |
|  | [**`r q3_close %>% format("%m/%d")`**]{.quiz-row} |  |  |  |  | **Quiz 3 closes \@ 11pm** |  |  |  |  |  |
| [ ]{.week-row} |  |  |  |  |  |  |  |  |  |  |  |
| 11 | `r w11d1 %>% format("%m/%d")` |  |  |  |  | Catch-up day |  |  |  |  |  |
|  | [**`r hw7 %>% format("%m/%d")`**]{.pract-row} |  |  |  |  | **Optional HW 7 due 11 pm** |  |  |  |  |  |
|  | **`r proj %>% format("%m/%d")`** |  |  |  |  | [**Final Project: Clinician Brief due 11pm**]{.proj-row} |  |  |  |  |  |
:::
