---
title: "Schedule"
date-modified: "today"
format: 
  html:
    link-external-newwindow: true
    page-layout: full
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(here)
source(here("class_dates.R"))
```

| Week | Date | Key Info | Exit tix | Record-ing | Lesson | Topic | [TB](https://bookdown.org/kevin_davisross/probsim-book/) | Slides HTML | Slides PDF | Slides Notes | Muddy Points |
|------|------|:----:|:----:|:----:|------|------|------|:----:|:----:|:----:|:----:|
| 1 | `{r} w1d1 %>% format("%m/%d")` | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/00_Intro/00_Intro_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUOUcyWVVIQU5QR0lGSU4zWjE5M0dIWlMzRiQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_550_25F/Student_files_BSTA_550/Recordings/00_Welcome.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=AthcXF)]{style="color:#f8f5f0;"} |  | Welcome |  | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/00_Intro/00_Intro.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/00_Intro/00_Intro.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  |  | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_550_25F/Student_files_BSTA_550/Recordings/01_Probability_01.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=mCz24v)]{style="color:#f8f5f0;"} [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_550_25F/Student_files_BSTA_550/Recordings/01_Probability_02.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=KBn1gT)]{style="color:#f8f5f0;"} | 1 | Introduction to Probability | 1.1, 2.1, 2.2, 2.4.1 | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/01_Probability/01_Probability.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/01_Probability/01_Probability.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/01_Probability/01_Probability_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/01_Probability/01_Probability_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | `{r} w1d2 %>% format("%m/%d")` | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/02_Simulations/02_Simulations_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhURUlRNE04N1dFT0JMTVhZMk40SVYxV1JIViQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_550_25F/Student_files_BSTA_550/Recordings/02_Simulations.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=3oMNFO)]{style="color:#f8f5f0;"} | 2 | Introduction to Simulations | 2.3, 2.5 | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/02_Simulations/02_Simulations.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/02_Simulations/02_Simulations.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/02_Simulations/02_Simulations_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/02_Simulations/02_Simulations_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | [**`r hw0 %>% format("%m/%d")`**]{style="color:#006a4e;"} |  |  |  |  | [**HW 0 due 11pm**]{style="color:#006a4e;"} |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |
| 2 | `{r} w2d1 %>% format("%m/%d")` | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/03_Lang_prob/03_Lang_prob_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUQ1BFWU5SU0ZaQUVPQjJUUDIxS0JVQjJXMiQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_550_25F/Student_files_BSTA_550/Recordings/03_Lang_prob_01.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=C2nUI4)]{style="color:#f8f5f0;"} [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_550_25F/Student_files_BSTA_550/Recordings/03_Lang_prob_02.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=gr4wV7)]{style="color:#f8f5f0;"} [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_550_25F/Student_files_BSTA_550/Recordings/03_Lang_prob_03.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=1m19wU)]{style="color:#f8f5f0;"} | 3 | Language of Probability | 2.2, 2.4 | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/03_Lang_prob/03_Lang_prob.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/03_Lang_prob/03_Lang_prob.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/03_Lang_prob/03_Lang_prob_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/03_Lang_prob/03_Lang_prob_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | `{r} w2d2 %>% format("%m/%d")` | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/04_Rules_of_prob/04_Rules_of_prob_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUNEJURTlCQ043NUIzSUNBVVdLMFhTNE5MNiQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_550_25F/Student_files_BSTA_550/Recordings/04_Rules_of_prob_01.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=jjzboT)]{style="color:#f8f5f0;"} [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_550_25F/Student_files_BSTA_550/Recordings/04_Rules_of_prob_02.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=lb1sqA)]{style="color:#f8f5f0;"} | 4 | Rules of Probability | 2.7, 3.3-3.5 | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/04_Rules_of_prob/04_Rules_of_prob.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/04_Rules_of_prob/04_Rules_of_prob.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/04_Rules_of_prob/04_Rules_of_prob_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/04_Rules_of_prob/04_Rules_of_prob_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | [**`r hw1 %>% format("%m/%d")`**]{style="color:#006a4e;"} |  |  |  |  | [**HW 1 due 11pm**]{style="color:#006a4e;"} |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |
| 3 | `r w3d1 %>% format("%m/%d")` | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/06_Calculus_review/06_Calculus_review_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUMVBEWVcwQ1UyVUU2TUhLVE1JTFpGNkNORiQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_550_25F/Student_files_BSTA_550/Recordings/06_Calculus_review.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=eoeGIb)]{style="color:#f8f5f0;"} | 6 | Async optional video: Calculus Review |  | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/06_Calculus_review/06_Calculus_review.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/06_Calculus_review/06_Calculus_review.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/06_Calculus_review/06_Calculus_review_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/06_Calculus_review/06_Calculus_review_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | `r w3d2 %>% format("%m/%d")` | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/05_Equally_likely_outcomes/05_Equally_likely_outcomes_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUMDJOQzRVOUxaWTNaV0g5WFFNNkZBT0hOMCQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_550_25F/Student_files_BSTA_550/Recordings/05_Equally_likely_outcomes.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=OmANo8)]{style="color:#f8f5f0;"} | 5 | Equally Likely Outcomes | 3.6 | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/05_Equally_likely_outcomes/05_Equally_likely_outcomes.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/05_Equally_likely_outcomes/05_Equally_likely_outcomes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/05_Equally_likely_outcomes/05_Equally_likely_outcomes_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/05_Equally_likely_outcomes/05_Equally_likely_outcomes_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | [**`r hw2 %>% format("%m/%d")`**]{style="color:#006a4e;"} |  |  |  |  | [**HW 2 due 11 pm**]{style="color:#006a4e;"} |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |
| 4 | `r w4d1 %>% format("%m/%d")` | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/07_pmfs/07_pmfs_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUQTBPMzhJMDNZV1VFSERaUk9VWkxaRjQxRyQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_550_25F/Student_files_BSTA_550/Recordings/07_pmfs.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=sIVEiu)]{style="color:#f8f5f0;"} | 7 | pmfs | 4.1, 4.2 | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/07_pmfs/07_pmfs.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/07_pmfs/07_pmfs.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/07_pmfs/07_pmfs_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/07_pmfs/07_pmfs_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  |  |  |  | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_550_25F/Student_files_BSTA_550/Recordings/08_pdfs.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=P2trtP)]{style="color:#f8f5f0;"} | 8 | pdfs | 4.3 | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/08_pdfs/08_pdfs.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/08_pdfs/08_pdfs.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/08_pdfs/08_pdfs_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/08_pdfs/08_pdfs_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | `r w4d2 %>% format("%m/%d")` | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/09_CDFs/09_CDFs_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhURExZOFNKNkpTRldYVFAxTzczSzNVVVFGNSQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_550_25F/Student_files_BSTA_550/Recordings/09_CDFs.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=FbbEAq)]{style="color:#f8f5f0;"} | 9 | CDFs | 4.4 | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/09_CDFs/09_CDFs.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/09_CDFs/09_CDFs.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/09_CDFs/09_CDFs_notes.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**`r q1_open %>% format("%m/%d")`**]{style="color:#006a4e;"} |  |  |  |  | [**Quiz 1 opens \@ 3pm**]{style="color:#006a4e;"} |  |  |  |  |  |
|  | [**`r hw3 %>% format("%m/%d")`**]{style="color:#006a4e;"} |  |  |  |  | [**HW 3 due 11 pm**]{style="color:#006a4e;"} |  |  |  |  |  |
|  | [**`r q1_close %>% format("%m/%d")`**]{style="color:#006a4e;"} |  |  |  |  | [**Quiz 1 closes \@ 11pm**]{style="color:#006a4e;"} |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |
| 5 | `r w5d1 %>% format("%m/%d")` | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/10_Transformations/10_Transformations_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUNlNSSFVIUk05MkpWT1NaSzYxTFhYOTRURyQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_550_25F/Student_files_BSTA_550/Recordings/10_Transformations.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=iqlxg5)]{style="color:#f8f5f0;"} | 10 | Transformations of distributions | 4.6 | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/10_Transformations/10_Transformations.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/10_Transformations/10_Transformations.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/10_Transformations/10_Transformations_notes.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | `r w5d2 %>% format("%m/%d")` | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/11_Joint_distributions/11_Joint_distributions_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUQ1JHVlE0UkoxTUI4SE5HNk8yU0dFRlYyQyQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_550_25F/Student_files_BSTA_550/Recordings/11_Joint_distributions_01.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=XVWPgR)]{style="color:#f8f5f0;"} [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_550_25F/Student_files_BSTA_550/Recordings/11_Joint_distributions_02.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=DajVXN)]{style="color:#f8f5f0;"} [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_550_25F/Student_files_BSTA_550/Recordings/11_Joint_distributions_03.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=isjLFA)]{style="color:#f8f5f0;"} | 11 | Joint distributions | 4.7 | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/11_Joint_distributions/11_Joint_distributions.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/11_Joint_distributions/11_Joint_distributions.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/11_Joint_distributions/11_Joint_distributions_notes.pdf)]{style="color:#f8f5f0;"} [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/11_Joint_distributions/11_Joint_distributions_notes_02.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/11_Joint_distributions/11_Joint_distributions_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | [**`r hw4 %>% format("%m/%d")`**]{style="color:#006a4e;"} |  |  |  |  | [**HW 4 due 11 pm**]{style="color:#006a4e;"} |  |  |  |  |  |
|  | [**`r hw4 %>% format("%m/%d")`**]{style="color:#006a4e;"} |  |  |  |  | [[**Midterm feedback due \@ 11pm**](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUOU02QjcwQTZINThKVTMxMDRRWTZHWUtYMSQlQCNjPTEu)]{style="color:#006a4e;"} |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |
| 6 | `r w6d1 %>% format("%m/%d")` | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/12_Independence_conditioning/12_Independence_Conditioning_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUMUdEVFROQVhIUjBMUkFTNE5UNDNaNVNFTCQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_550_25F/Student_files_BSTA_550/Recordings/12_Independence_conditioning_01.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=QGwtra)]{style="color:#f8f5f0;"} [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_550_25F/Student_files_BSTA_550/Recordings/12_Independence_conditioning_02.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=YaCSnn)]{style="color:#f8f5f0;"} | 12 | Independence and Conditioning | 4.8, 4.9 | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/12_Independence_Conditioning/12_Independence_conditioning.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/12_Independence_Conditioning/12_Independence_conditioning.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/12_Independence_Conditioning/12_Independence_conditioning_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/12_Independence_Conditioning/12_Independence_conditioning_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | `r w6d2 %>% format("%m/%d")` | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/11_Joint_distributions/11_Joint_distributions_review_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUQlo5VUFQVEYxOVJIVkMwNDM2RExEMlFQNyQlQCNjPTEu)]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_550_25F/Student_files_BSTA_550/Recordings/11_Joint_distributions_03.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=2Mbplt) |  | Review of joint distributions, independence, conditioning |  | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/11_Joint_distributions/11_Joint_distributions_review.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/11_Joint_distributions/11_Joint_distributions.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/11_Joint_distributions/11_Joint_distributions_notes.pdf)]{style="color:#f8f5f0;"} [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/11_Joint_distributions/11_Joint_distributions_notes_02.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/11_Joint_distributions/11_Joint_distributions_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | [**`r q2_open %>% format("%m/%d")`**]{style="color:#006a4e;"} |  |  |  |  | [**Quiz 2 opens \@ 11pm**]{style="color:#006a4e;"} |  |  |  |  |  |
|  | [**`r hw5 %>% format("%m/%d")`**]{style="color:#006a4e;"} |  |  |  |  | [**HW 5 due 11 pm**]{style="color:#006a4e;"} |  |  |  |  |  |
|  | [**`r q2_close %>% format("%m/%d")`**]{style="color:#006a4e;"} |  |  |  |  | [**Quiz 2 closes \@ 11pm**]{style="color:#006a4e;"} |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |
| 7 | `r w7d1 %>% format("%m/%d")` | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/13_Expected_Values/13_Expected_Values_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUMzlDTE9aQlpTSFU5Njg0NVhWTjBYMU9RTyQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_550_25F/Student_files_BSTA_550/Recordings/13_Expected_values.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=02kLlp)]{style="color:#f8f5f0;"} | 13 | Expected Values | 5.1 | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/13_Expected_Values/13_Expected_Values.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/13_Expected_Values/13_Expected_Values.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/13_Expected_Values/13_Expected_Values_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/13_Expected_Values/13_Expected_Values_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | `r w7d2 %>% format("%m/%d")` | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/14_Variance/14_Variance_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUMDJKQ0JXVTRBSjI1TVVTNElNMlA0MTIxSCQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_550_25F/Student_files_BSTA_550/Recordings/14_Variance.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=pzibdn)]{style="color:#f8f5f0;"} [{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_550_25F/Student_files_BSTA_550/Recordings/14_Variance_02.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=5pKcfW) | 14 | Variance | 5.2, 5.3 | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/14_Variance/14_Variance.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/14_Variance/14_Variance.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/14_Variance/14_Variance_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/14_Variance/14_Variance_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | [**`r hw6 %>% format("%m/%d")`**]{style="color:#006a4e;"} |  |  |  |  | [**HW 6 due 11 pm**]{style="color:#006a4e;"} |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |
| 8 | `r w8d1 %>% format("%m/%d")` | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/15_Discrete_RVs/15_Discrete_RVs_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUNDZHTkRXUUNFMkc2VEo5SlJCRUkzRVZWMSQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_550_25F/Student_files_BSTA_550/Recordings/15_Discrete_RVs.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=6OpuN7)]{style="color:#f8f5f0;"} [{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_550_25F/Student_files_BSTA_550/Recordings/15_Discrete_RVs_02.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=u7ChSj) | 15 | Important discrete RVs | 6 | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/15_Discrete_RVs/15_Discrete_RVs.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/15_Discrete_RVs/15_Discrete_RVs.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/15_Discrete_RVs/15_Discrete_RVs_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/15_Discrete_RVs/15_Discrete_RVs_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | `r w8d2 %>% format("%m/%d")` | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/16_Cont_RVs/16_Cont_RVs_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUMk83UDcwU0g1SE9NNE9LRU9CRllKWDlWTiQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_550_25F/Student_files_BSTA_550/Recordings/16_Continuous_RVs_01.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=30ZRpU)]{style="color:#f8f5f0;"} [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_550_25F/Student_files_BSTA_550/Recordings/16_Cont_RVs_02.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=lmuUuw)]{style="color:#f8f5f0;"} | 16 | Important continuous RVS | 7 | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/16_Cont_RVs/16_Cont_RVs.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/16_Cont_RVs/16_Cont_RVs.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/16_Cont_RVs/16_Cont_RVs_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/16_Cont_RVs/16_Cont_RVs_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | [**`r hw7 %>% format("%m/%d")`**]{style="color:#006a4e;"} |  |  |  |  | [**HW 7 due 11 pm**]{style="color:#006a4e;"} |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |
| 9 | `r w9d1 %>% format("%m/%d")` | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/17_Central_Limit_Theorem/17_Central_Limit_Theorem_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUQkszTk9SVDJYTVJHNjJVU0Y4TTBCTTQ0UyQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_550_25F/Student_files_BSTA_550/Recordings/37_CLT.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=yq7D8w)]{style="color:#f8f5f0;"} [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_550_25F/Student_files_BSTA_550/Recordings/17_CLT.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=ygdAde)]{style="color:#f8f5f0;"} [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_550_25F/Student_files_BSTA_550/Recordings/17_CLT_02.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=zNyxqM)]{style="color:#f8f5f0;"} | 17 | Central limit theorem | 8.1 | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/17_Central_Limit_Theorem/17_Central_Limit_Theorem.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/17_Central_Limit_Theorem/17_Central_Limit_Theorem.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/17_Central_Limit_Theorem/17_Central_Limit_Theorem_notes.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | `r w9d2 %>% format("%m/%d")` |  |  |  |  | No class |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |
| 10 | `r w10d1 %>% format("%m/%d")` |  |  |  |  | No class |  |  |  |  |  |
|  | `r w10d2 %>% format("%m/%d")` | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/18_Moment_Generating_Functions/18_Moment_Generating_Functions_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUQ1JHN1VCMEYxNDNCQTc3SlA5WFFYR01YWCQlQCNjPTEu)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_550_25F/Student_files_BSTA_550/Recordings/18_MGFs.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=fe3GpH)]{style="color:#f8f5f0;"} | 18 | Moment Generating functions |  | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/18_Moment_Generating_Functions/18_Moment_Generating_Functions.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/18_Moment_Generating_Functions/18_Moment_Generating_Functions.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/18_Moment_Generating_Functions/18_Moment_Generating_Functions_notes.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**`r q3_open %>% format("%m/%d")`**]{style="color:#006a4e;"} |  |  |  |  | [**Quiz 3 opens \@ 3pm**]{style="color:#006a4e;"} |  |  |  |  |  |
|  | [**`r hw8 %>% format("%m/%d")`**]{style="color:#006a4e;"} |  |  |  |  | [**HW 8 due 11 pm**]{style="color:#006a4e;"} |  |  |  |  |  |
|  | [**`r q3_close %>% format("%m/%d")`**]{style="color:#006a4e;"} |  |  |  |  | [**Quiz 3 closes \@ 11pm**]{style="color:#006a4e;"} |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |
| 11 | `r w11d1 %>% format("%m/%d")` |  |  |  |  | Catch-up day |  |  |  |  |  |
|  | [**`r hw9 %>% format("%m/%d")`**]{style="color:#006a4e;"} |  |  |  |  | [**Optional HW 9 due 11 pm**]{style="color:#006a4e;"} |  |  |  |  |  |
