{
  "hash": "e5cadfdb6265648b2f25e205f543a055",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lesson 11: Transformations\"\nauthor: \"Nicky Wakim\"\ntitle-slide-attributes:\n    data-background-color: \"#006a4e\"\ndate: \"2025-10-27\"\nformat: \n  revealjs:\n    theme: \"../simple_NW.scss\"\n    slide-number: true\n    show-slide-number: all\n    width: 1955\n    height: 1100\n    footer: Lesson 11 Slides\n    html-math-method: mathjax\n---\n\n\n\n\n\n## Distributions of transformations of random variables {#cdf-method}\n\nIt is common in many scientific, mathematical, and statistical context to transform variables.\nA function of a random variable is a random variable: if $X$ is a random variable and $g$ is a function then $Y=g(X)$ is a random variable.\nSince $g(X)$ is a random variable it has a distribution.\nIn general, the distribution of $g(X)$ will have a different shape than the distribution of $X$.\nThis section discusses some techniques for determining how a transformation changes the shape of a distribution.\n\n## Linear rescaling\n\nIn general, the distribution of $g(X)$ will have a different shape than the distribution of $X$.\nThe exception is when $g$ is a linear rescaling.\n\nA **linear rescaling** is a transformation of the form $g(u) = a + bu$, where $a$ (intercept) and $b$ (slope[^distribution-9]) are constants.\nFor example, converting temperature from Celsius to Fahrenheit using $g(u) = 32 + 1.8u$ is a linear rescaling.\n\n[^distribution-9]: You might be familiar with \"$mx+b$\" where $b$ denotes the intercept.\n    In Statistics, $b$ is often used to denote slope.\n    For example, in R `abline(a = 32, b = 1.8)` draws a line with intercept 32 and slope 1.8.\n\nA linear rescaling \"preserves relative interval length\" in the following sense.\n\n-   If interval A and interval B have the same length in the original measurement units, then the rescaled intervals A and B will have the same length in the rescaled units. For example, [0, 10] and [10, 20] Celsius, both length 10 degrees Celsius, correspond to [32, 50] and [50, 68] Fahrenheit, both length 18 degrees Fahrenheit.\n-   If the ratio of the lengths of interval A and B is $r$ in the original measurement units, then the ratio of the lengths in the rescaled units is also $r$. For example, [10, 30] is twice as long as [0, 10] in Celsius; for the corresponding Fahrenheit intervals, [50, 86] is twice as long as [32, 50].\n\n## linear\n\nThink of a linear rescaling as just a consistent relabeling of the variable axis; every 1 unit increment in the original scale corresponds to a $b$ unit increment in the linear rescaling.\n\n\n\n::: {.cell}\n\n:::\n\n\n\nSuppose that SAT Math score $X$ follows a Uniform(200, 800) distribution.\n(It doesn't but go with in for now).\nOne way to simulate values of $X$ is to simulate values of $U$ from a Uniform(0, 1) distribution and let $X = 200 + (800 - 200)U= 200 + 600U$.\nThen $X$ is a linear rescaling of $U$, and $X$ takes values in the interval [200, 800].\nWe can define and simulate values of $X$ in Symbulate.\nBefore looking at the results, sketch a plot of the distribution of $X$ and make an educated guess for its mean and standard deviation.\n\n\n##\n\nWe see that $X$ has a Uniform(200, 800) distribution.\nThe linear rescaling changes the range of possible values, but the general shape of the distribution is still Uniform.\nWe can see why by inspecting a few intervals on both the original and revised scale.\n\n| Interval of $U$ values | Probability that $U$ lies in the interval | Interval of $X$ values | Probability that $X$ lies in the interval |\n|---------------:|--------------------:|---------------:|--------------------:|\n|             (0.0, 0.1) |                                       0.1 |             (200, 260) |                          $\\frac{60}{600}$ |\n|             (0.9, 1.0) |                                       0.1 |             (740, 800) |                          $\\frac{60}{600}$ |\n|             (0.0, 0.2) |                                       0.2 |             (200, 320) |                         $\\frac{120}{600}$ |\n\nFor a Uniform distribution the long run average is the midpoint of possible values.\nThe long run average value of $U$ is 0.5, and of $X$ is 500.\nThese two values are related through the same formula mapping $U$ to $X$ values: $500 = 200 + 600\\times 0.5$.\n\n## \n\nFor a Uniform distribution, the standard deviation the about 0.289 times the length of the interval: $|b-a|/\\sqrt{12}$.\nThe standard deviation of $U$ is about 0.289, and of $X$ is about 173.\n\n\nThe standard deviation of $X$ is 600 times the standard deviation of $U$.\nMultiplying the $U$ values by 600 rescales the distance between the values.\nTwo values of $U$ that are 0.1 units apart correspond to two values of $X$ that are 60 units apart.\nA $U$ value of 0.6 is 0.1 units above the mean of $U$, and the corresponding $X$ value 560 is 60 units about the mean of $X$.\nHowever, adding the constant 200 to all values just shifts the distribution and does affect degree of variability.\n\n1.  Does $V$ result from a linear rescaling of $U$?\n2.  What are the possible values of $V$?\n3.  Is $V$ the same random variable as $U$?\n4.  Find $\\IP(U \\le 0.1)$ and $\\IP(V \\le 0.1)$.\n5.  Sketch a plot of what the histogram of many simulated values of $V$ would look like.\n6.  Does $V$ have the same distribution as $U$?\n\n## \nLet's consider a non-uniform example.\nNow let's suppose that SAT Math score $X$ follows a Normal(500, 100) distribution.\nWe can simulate values of $X$ by simulating $Z$ from the standard Normal(0, 1) distribution and setting $X = 500 + 100Z$.\n(Remember that the standard Normal spinner returns standardized values, so $Z = 1$ corresponds to 1 standard deviation above the mean, that is, $X= 600$.) The reason this works is because the linear rescaling doesn't change the Normal shape.\n\n\n\nThe linear rescaling changes the range of observed values; almost all of the values of $Z$ lie in the interval $(-3, 3)$ while almost all of the values of $X$ lie in the interval $(200, 800)$.\nHowever, the distribution of $X$ still has the general Normal shape.\nThe means are related by the conversion formula: $500 = 500 + 100 \\times 0$.\nMultiplying the values of $Z$ by 100 rescales the distance between values; two values of $Z$ that are 1 unit apart correspond to two values of $X$ that are 100 units apart.\nHowever, adding the constant 500 to all the values just shifts the center of the distribution and does not affect variability.\nTherefore, the standard deviation of $X$ is 100 times the standard deviation of $Z$.\n\n##\n\nIn general, if $Z$ has a Normal(0, 1) distribution then $X = \\mu + \\sigma Z$ has a Normal($\\mu$, $\\sigma$) distribution.\n\n1.  Is $Y$ the same random variable as $X$?\n2.  Does $Y$ have the same distribution as $X$?\n\n1.  Donny Don't says that the distribution of $-Z$ will look like an \"upside-down bell\". Is Donny correct? If not, explain why not and describe the distribution of $-Z$.\n2.  Donny Don't says that the standard deviation of $-Z$ is -1. Is Donny correct? If not, explain why not and determine the standard deviation of $-Z$.\n\n## Summary\n\n-   A linear rescaling is a transformation of the form $g(u) = a + bu$.\n-   A linear rescaling of a random variable does not change the basic shape of its distribution, just the range of possible values.\n    -   However, remember that the possible values are part of the distribution. So a linear rescaling does technically change the distribution, even if the basic shape is the same. (For example, Normal(500, 100) and Normal(0, 1) are two different distributions.)\n-   A linear rescaling transforms the mean in the same way the individual values are transformed.\n-   Adding a constant to a random variable does not affect its standard deviation.\n-   Multiplying a random variable by a constant multiplies its standard deviation by the *absolute value* of the constant.\n-   Whether in the short run or the long run, \\begin{align*}\n    \\text{Average of $a+bX$} & = a+b(\\text{Average of $X$})\\\\\n    \\text{SD of $a+bX$} & = |b|(\\text{SD of $X$})\\\\\n    \\text{Variance of $a+bX$} & = b^2(\\text{Variance of $X$})\n    \\end{align*}\n-   If $U$ has a Uniform(0, 1) distribution then $X = a + (b-a)U$ has a Uniform($a$, $b$) distribution.\n-   If $Z$ has a Normal(0, 1) distribution then $X = \\mu + \\sigma Z$ has a Normal($\\mu$, $\\sigma$) distribution.\n-   Remember, do NOT confuse a random variable with its distribution.\n    -   The random variable is the numerical quantity being measured\n    -   The distribution is the long run pattern of variation of many observed values of the random variable\n\n## Nonlinear transformations of random variables {#sim-nonlinear}\n\nA linear rescaling does not change the shape of a distribution, only the range of possible values.\nBut what about a nonlinear transformation, like a logarithmic or square root transformation?\nIn contrast to a linear rescaling, a nonlinear rescaling does *not* preserve relative interval length, so we might expect that a nonlinear rescaling can change the shape of a distribution.\nWe'll investigate by considering the Uniform(0, 1) spinner and a logarithmic[^distribution-10] transformation.\n\n[^distribution-10]: As in many other contexts and programming languages, in this text any reference to logarithms or $\\log$ refers to natural (base $e$) logarithms.\n    In the instances we need to consider another base, we'll make that explicit.\n\nLet $U$ represent the result of a single spin of the Uniform(0, 1) spinner.\nWe'll basically consider $\\log(U)$, but this leads to to two minor technicalities.\n\n-   Since $U\\in[0, 1]$, $\\log(U)\\le 0$. To obtain positive values we consider $-\\log(U)$, which takes values in $[0,\\infty)$.\n-   Technically, applying $-\\log(u)$ to the values on the axis of the Uniform(0, 1) spinner, the resulting values would decrease from $\\infty$ to 0 clockwise. To make the values start at 0 and increase to $\\infty$ clockwise, we consider $-\\log(1-U)$. (We saw in the previous section the transformation $u \\to 1-u$ basically just changes direction from clockwise to counterclockwise.)\n\n## \n\nTherefore, it's a little more convenient to consider the random variable $X=-\\log(1-U)$ which takes values in $[0,\\infty)$.\nIt also turns out, as we saw in earlier, that $-\\log(1-u)$ is the quantile function of the Exponential(1) distribution.\nWe have already seen that $X$ has an Exponential(1) distribution.\nNow we'll take a closer look why.\n\nThe following code defines $X$ and plots a few simulated values.\n\n\nNotice that values near 0 occur with higher frequency than larger values.\nFor example, there are many more simulated values of $X$ that lie in the interval $[0, 1]$ than in the interval $[3, 4]$, even though these intervals both have length 1.\nLet's see why this is happening.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Interval of U |Length of U interval |Probability |Interval of X |Length of X interval |\n|:-------------|:--------------------|:-----------|:-------------|:--------------------|\n|(0, 0.1)      |                     |            |              |                     |\n|(0.1, 0.2)    |                     |            |              |                     |\n|(0.2, 0.3)    |                     |            |              |                     |\n|(0.3, 0.4)    |                     |            |              |                     |\n|(0.4, 0.5)    |                     |            |              |                     |\n|(0.5, 0.6)    |                     |            |              |                     |\n|(0.6, 0.7)    |                     |            |              |                     |\n|(0.7, 0.8)    |                     |            |              |                     |\n|(0.8, 0.9)    |                     |            |              |                     |\n|(0.9, 1)      |                     |            |              |                     |\n\n\n:::\n:::\n\n\n\n##\n\nPlug the endpoints into the conversion formula $u\\mapsto -\\log(1-u)$ to find the corresponding $X$ interval.\nFor example, the $U$ interval $(0.1, 0.2)$ corresponds to the $X$ interval $(-\\log(1-0.1), -\\log(1-0.2)) = (0.105, 0.223)$.\nSince $U$ has a Uniform(0, 1) distribution the probability is just the length of the $U$ interval.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Interval of U | Length of U interval| Probability|Interval of X  | Length of X interval|\n|:-------------|--------------------:|-----------:|:--------------|--------------------:|\n|(0, 0.1)      |                  0.1|         0.1|(0, 0.105)     |                0.105|\n|(0.1, 0.2)    |                  0.1|         0.1|(0.105, 0.223) |                0.118|\n|(0.2, 0.3)    |                  0.1|         0.1|(0.223, 0.357) |                0.134|\n|(0.3, 0.4)    |                  0.1|         0.1|(0.357, 0.511) |                0.154|\n|(0.4, 0.5)    |                  0.1|         0.1|(0.511, 0.693) |                0.182|\n|(0.5, 0.6)    |                  0.1|         0.1|(0.693, 0.916) |                0.223|\n|(0.6, 0.7)    |                  0.1|         0.1|(0.916, 1.204) |                0.288|\n|(0.7, 0.8)    |                  0.1|         0.1|(1.204, 1.609) |                0.405|\n|(0.8, 0.9)    |                  0.1|         0.1|(1.609, 2.303) |                0.693|\n|(0.9, 1)      |                  0.1|         0.1|(2.303, Inf)   |                  Inf|\n\n\n:::\n:::\n\n\n\n## \n\nWe see that the logarithmic transformation does not preserve relative interval length.\nEach of the original intervals of $U$ values has the same length, but the nonlinear logarithmic transformation \"stretches out\" these intervals in different ways.\nThe probability that $U$ lies in each of these intervals is 0.1.\nAs the transformation stretches the intervals, the 0.1 probability gets \"spread\" over intervals of different length.\nSince probability/relative frequency is represented by area in a histogram, if two regions of differing length have the same area, then they must have different heights.\nThus the shape of the distribution of $X$ will not be Uniform.\n\nThe following plot illustrates the results of Example \\@ref(exm:uniform-log-transform-calcs).\nEach bar in the top histogram corresponds to the same color bar in the bottom histogram.\nAll bars have area 0.1.\nIn the top histogram, the bins have equal width so the heights are the same.\nHowever, in the bottom histogram the bars have different widths but the same area, so they must have different heights, and we start to see where the Exponential(1) shape comes from.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](11_Transformations_files/figure-revealjs/unnamed-chunk-4-1.png){width=960}\n:::\n:::\n\n\n\n##\n\nThe following example provides a similar illustration, but from the reverse perspective.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Interval of X |Length of X interval |Probability |Interval of U |Length of U interval |\n|:-------------|:--------------------|:-----------|:-------------|:--------------------|\n|(0, 0.5)      |                     |            |              |                     |\n|(0.5, 1)      |                     |            |              |                     |\n|(1, 1.5)      |                     |            |              |                     |\n|(1.5, 2)      |                     |            |              |                     |\n|(2, 2.5)      |                     |            |              |                     |\n|(2.5, 3)      |                     |            |              |                     |\n|(3, 3.5)      |                     |            |              |                     |\n|(3.5, 4)      |                     |            |              |                     |\n|(4, 4.5)      |                     |            |              |                     |\n|(4.5, 5)      |                     |            |              |                     |\n\n\n:::\n:::\n\n\n\n## \n\nThe corresponding $U$ intervals are obtained by applying the inverse transformation $v\\mapsto 1-e^{-v}$.\nFor example, the $X$ interval $(0.5, 1)$ corresponds to the $U$ interval $(1-e^{-0.5}, 1-e^{-1}) = (0.393, 0.632)$.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Interval of X | Length of X interval| Probability|Interval of U  | Length of U interval|\n|:-------------|--------------------:|-----------:|:--------------|--------------------:|\n|(0, 0.5)      |                  0.5|       0.393|(0, 0.393)     |                0.393|\n|(0.5, 1)      |                  0.5|       0.239|(0.393, 0.632) |                0.239|\n|(1, 1.5)      |                  0.5|       0.145|(0.632, 0.777) |                0.145|\n|(1.5, 2)      |                  0.5|       0.088|(0.777, 0.865) |                0.088|\n|(2, 2.5)      |                  0.5|       0.053|(0.865, 0.918) |                0.053|\n|(2.5, 3)      |                  0.5|       0.032|(0.918, 0.95)  |                0.032|\n|(3, 3.5)      |                  0.5|       0.020|(0.95, 0.97)   |                0.020|\n|(3.5, 4)      |                  0.5|       0.012|(0.97, 0.982)  |                0.012|\n|(4, 4.5)      |                  0.5|       0.007|(0.982, 0.989) |                0.007|\n|(4.5, 5)      |                  0.5|       0.004|(0.989, 0.993) |                0.004|\n\n\n:::\n:::\n\n\n\nSince $U$ has a Uniform(0, 1) distribution the probability is just the length of the $U$ interval.\nEach of the $X$ intervals has the same length but they correspond to intervals of differing length in the original $U$ scale, and hence intervals of different probability.\n\n## \n\nThe following plot illustrates the results of Example \\@ref(exm:uniform-log-transform-calcs2) (plots on the right).\nThese two examples give some insight into how the transformed random variable $X = -\\log(1-U)$ has an Exponential(1) distribution.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](11_Transformations_files/figure-revealjs/unnamed-chunk-7-1.png){width=960}\n:::\n:::\n\n\n\n\"Spreadsheet\" calculations like those in the previous two examples can help when sketching the distribution of a transformed random variable.\n\n<!-- It should be clear that the simulated values of $X$ do not follow a Uniform distribution.  Values near 0 occur with greater frequency than larger values.  The non-linear log transformation changes the shape of the distribution. -->\n\n<!-- To get some intuition behind why the shape changes, consider the following illustration. Consider intervals in increments of 0.1, starting from 0, on the original [0, 1] scale.  These intervals each have length 0.1 and so each have probability 0.1 according to the uniform probability measure.  Now consider the corresponding transformed intervals. -->\n\n<!-- - [0, 0.1] maps to^[Each of these values is obtained from the transformation $u\\mapsto-\\log(1-u)$, e.g. $-\\log(1-0.1)\\approx 0.105$.] [0, 0.105], an interval of length 0.105. -->\n\n<!-- - [0.1, 0.2] maps to [0.105, 0.223], an interval of length 0.118. -->\n\n<!-- - [0.2, 0.3] maps to [0.223, 0.357], an interval of length 0.134. -->\n\n<!-- - [0.3, 0.4] maps to [0.357, 0.511], an interval of length 0.154. -->\n\n<!-- - [0.4, 0.5] maps to [0.511, 0.693], an interval of length 0.182, and so on. -->\n\n<!-- - [0, 1] corresponds to^[Each of these values is obtained by applying the inverse transformation $u\\mapsto 1-e^{-u}$, e.g. $1-e^{-1}\\approx 0.632$] [0, 0.632], and interval with probability 0.632. -->\n\n<!-- - [1, 2] corresponds to [0.632, 0.865], and interval with probability 0.233. -->\n\n<!-- - [2, 3] corresponds to [0.865, 0.950], and interval with probability 0.086. -->\n\n<!-- Notice that the shape of the histogram depicting the simulated values of $X$ appears that it can be approximated by a smooth curve.  This smooth curve is an idealized model of what would happen in the long run if -->\n\n<!--   - we kept simulating more and more values, and -->\n\n<!--   - made the histogram bin widths smaller and smaller. -->\n\n<!-- The following plot illustrates the results of 100,000 simulated values of $X$ summarized in a histogram with 1000 bins.  -->\n\nFor a linear rescaling, we could just plug the mean of the original variable into the conversion formula to find the mean of the transformed variable.\nHowever, this will not work for nonlinear transformations.\n\n## \n\nWe know that since $U$ has a Uniform(0, 1) distribution its long run average value is 0.5, and since $X$ has an Exponential(1) distribution its long run average value is 1, but $-\\log(1 - 0.5) \\neq 1$.\nThe nonlinear \"stretching\" of the axis makes some value relatively larger and others relatively smaller than they were on the original scale, which influences the average.\nRemember, in general: whether in the short run or the long run $$\n\\text{Average of } g(X) \\neq g(\\text{Average of }X).\n$$\n\nRecall that a function of a random variable is also a random variable.\nIf $X$ is a random variable, then $Y=g(X)$ is also a random variable and so it has a probability distribution.\nUnless $g$ represents a linear rescaling, a transformation will change the shape of the distribution.\nSo the question is: what is the distribution of $g(X)$?\nWe'll focus on transformations of continuous random variables, in which case the key to answering the question is to work with cdfs.\n\n1.  Identify the possible values of $X$. (We have done this already, but this should always be your first step.)\n2.  Let $F_X$ denote the cdf of $X$. Find $F_X(1)$.\n3.  Find $F_X(2)$.\n4.  Find the cdf $F_X(x)$.\n5.  Find the pdf $f_X(x)$.\n6.  Why should we not be surprised that $X=-\\log(1-U)$ has cdf $F_X(x) = 1 - e^{-x}$? Hint: what is the function $u\\mapsto -\\log(1-u)$ in this case?\n\n\n(ref:cap-log-function-plot) A plot of the function $u\\mapsto -\\log(1-u)$. The dotted lines illustrate that $-\\log(1-u)\\le 1$ if and only if $u\\le 1-e^{-1}\\approx 0.632$.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![(ref:cap-log-function-plot)](11_Transformations_files/figure-revealjs/log-function-plot-1.png){width=960}\n:::\n:::\n\n\n\n##\n\nIf $X$ is a continuous random variable whose distribution is known, the **cdf method** can be used to find the pdf of $Y=g(X)$\n\n-   Determine the possible values of $Y$. Let $y$ represent a generic possible value of $Y$.\n-   The cdf of $Y$ is $F_Y(y) = \\IP(Y\\le y) = \\IP(g(X) \\le y)$.\n-   Rearrange $\\{g(X) \\le y\\}$ to get an event involving $X$. Warning: it is not always $\\{X \\le g^{-1}(y)\\}$. Sketching a picture of the function $g$ helps.\n-   Obtain an expression for the cdf of $Y$ which involves $F_X$ and some transformation of the value $y$.\n-   Differentiate the expression for $F_Y(y)$ with respect to $y$, and use what is known about $F'_X = f_X$, to obtain the pdf of $Y$. You will typically need to apply the chain rule when differentiating.\n\nYou will need to use information about $X$ at some point in the last step above.\nYou can either:\n\n-   Plug in the *cdf* of $X$ and then differentiate with respect to $y$.\n-   Differentiate with respect to $y$ and then plug in the *pdf* of $X$.\n\nEither way gets you to the correct answer, but depending on the problem one way might be easier than the other.\nWe'll illustrate both methods in the next example.\n\n\n1.  Identify the possible values of $Y$.\n2.  Sketch the pdf of $Y$. Hint: consider a few equally spaced intervals of $Y$ values and see what $X$ values they correspond to.\n3.  Run a simulation to approximate the pdf of $Y$.\n4.  Find $F_Y(0.49)$.\n5.  Use the cdf method to find the pdf of $Y$. Is the pdf consistent with your simulation results?\n\n\n(ref:cap-square-function-plot) A plot of the function $x\\mapsto x^2$ for $-1<x<1$. The dotted lines illustrate that $x^2\\le 0.49$ if and only if $-\\sqrt{0.49}\\le x\\le \\sqrt{0.49}$.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![(ref:cap-square-function-plot)](11_Transformations_files/figure-revealjs/square-function-plot-1.png){width=960}\n:::\n:::\n\n\n\nThe table below helps us see how the transformation $Y = X^2$ \"pushes\" density towards 0 if $X$ has a Uniform(-1, 1) distribution.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;position: sticky; top:0; background-color: #FFFFFF;\"> Y interval </th>\n   <th style=\"text-align:left;position: sticky; top:0; background-color: #FFFFFF;\"> X interval </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> Length of X interval </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> Probability </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> Length of Y interval </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> Height of Y interval </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> (0, 0.1) </td>\n   <td style=\"text-align:left;\"> (-0.3162, 0) U (0,0.3162) </td>\n   <td style=\"text-align:right;\"> 0.6324 </td>\n   <td style=\"text-align:right;\"> 0.3162 </td>\n   <td style=\"text-align:right;\"> 0.1 </td>\n   <td style=\"text-align:right;\"> 3.162 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> (0.1, 0.2) </td>\n   <td style=\"text-align:left;\"> (-0.4472, -0.3162) U (0.3162,0.4472) </td>\n   <td style=\"text-align:right;\"> 0.2620 </td>\n   <td style=\"text-align:right;\"> 0.1310 </td>\n   <td style=\"text-align:right;\"> 0.1 </td>\n   <td style=\"text-align:right;\"> 1.310 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> (0.2, 0.3) </td>\n   <td style=\"text-align:left;\"> (-0.5477, -0.4472) U (0.4472,0.5477) </td>\n   <td style=\"text-align:right;\"> 0.2010 </td>\n   <td style=\"text-align:right;\"> 0.1005 </td>\n   <td style=\"text-align:right;\"> 0.1 </td>\n   <td style=\"text-align:right;\"> 1.005 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> (0.3, 0.4) </td>\n   <td style=\"text-align:left;\"> (-0.6325, -0.5477) U (0.5477,0.6325) </td>\n   <td style=\"text-align:right;\"> 0.1696 </td>\n   <td style=\"text-align:right;\"> 0.0848 </td>\n   <td style=\"text-align:right;\"> 0.1 </td>\n   <td style=\"text-align:right;\"> 0.848 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> (0.4, 0.5) </td>\n   <td style=\"text-align:left;\"> (-0.7071, -0.6325) U (0.6325,0.7071) </td>\n   <td style=\"text-align:right;\"> 0.1492 </td>\n   <td style=\"text-align:right;\"> 0.0746 </td>\n   <td style=\"text-align:right;\"> 0.1 </td>\n   <td style=\"text-align:right;\"> 0.746 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> (0.5, 0.6) </td>\n   <td style=\"text-align:left;\"> (-0.7746, -0.7071) U (0.7071,0.7746) </td>\n   <td style=\"text-align:right;\"> 0.1350 </td>\n   <td style=\"text-align:right;\"> 0.0675 </td>\n   <td style=\"text-align:right;\"> 0.1 </td>\n   <td style=\"text-align:right;\"> 0.675 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> (0.6, 0.7) </td>\n   <td style=\"text-align:left;\"> (-0.8367, -0.7746) U (0.7746,0.8367) </td>\n   <td style=\"text-align:right;\"> 0.1242 </td>\n   <td style=\"text-align:right;\"> 0.0621 </td>\n   <td style=\"text-align:right;\"> 0.1 </td>\n   <td style=\"text-align:right;\"> 0.621 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> (0.7, 0.8) </td>\n   <td style=\"text-align:left;\"> (-0.8944, -0.8367) U (0.8367,0.8944) </td>\n   <td style=\"text-align:right;\"> 0.1154 </td>\n   <td style=\"text-align:right;\"> 0.0577 </td>\n   <td style=\"text-align:right;\"> 0.1 </td>\n   <td style=\"text-align:right;\"> 0.577 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> (0.8, 0.9) </td>\n   <td style=\"text-align:left;\"> (-0.9487, -0.8944) U (0.8944,0.9487) </td>\n   <td style=\"text-align:right;\"> 0.1086 </td>\n   <td style=\"text-align:right;\"> 0.0543 </td>\n   <td style=\"text-align:right;\"> 0.1 </td>\n   <td style=\"text-align:right;\"> 0.543 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> (0.9, 1) </td>\n   <td style=\"text-align:left;\"> (-1, -0.9487) U (0.9487,1) </td>\n   <td style=\"text-align:right;\"> 0.1026 </td>\n   <td style=\"text-align:right;\"> 0.0513 </td>\n   <td style=\"text-align:right;\"> 0.1 </td>\n   <td style=\"text-align:right;\"> 0.513 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n\nWe can use the table to sketch a histogram.\n\n\n\nIf we continued the above process with narrower and narrower $Y$ intervals we would arrive at the smooth pdf given by $f_Y(y) = \\frac{1}{2\\sqrt{y}}, 0<y<1$; see the black curve in the plot below.\n\nNow we'll approximate the pdf via simulation.\nThe density blows up at 0 so it's hard for the chunky histogram to capture that, but we see the simulated values follow a distribution described by the smooth $f_Y(y) = \\frac{1}{2\\sqrt{y}}, 0<y<1$ in the black curve.\n\n\n\n",
    "supporting": [
      "11_Transformations_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}